// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDmOWVCwUU980mMqglNqYIfiwzOxRP5MQ',
    appId: '1:250491374057:web:bf0472acc6a2e37df86378',
    messagingSenderId: '250491374057',
    projectId: 'beatrivals-d8d2c',
    authDomain: 'beatrivals-d8d2c.firebaseapp.com',
    storageBucket: 'beatrivals-d8d2c.firebasestorage.app',
    measurementId: 'G-3E7Y42NWT2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKVhLLucXKGtwStP6p8kRZLtrdGDAFLVo',
    appId: '1:250491374057:android:fb0710515317a080f86378',
    messagingSenderId: '250491374057',
    projectId: 'beatrivals-d8d2c',
    storageBucket: 'beatrivals-d8d2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-WG_0Ic6-XN6Cz8iJL1pCYT7RcpkvWf8',
    appId: '1:250491374057:ios:5d44304c45c0e89af86378',
    messagingSenderId: '250491374057',
    projectId: 'beatrivals-d8d2c',
    storageBucket: 'beatrivals-d8d2c.firebasestorage.app',
    iosBundleId: 'com.example.beatrivalsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-WG_0Ic6-XN6Cz8iJL1pCYT7RcpkvWf8',
    appId: '1:250491374057:ios:5d44304c45c0e89af86378',
    messagingSenderId: '250491374057',
    projectId: 'beatrivals-d8d2c',
    storageBucket: 'beatrivals-d8d2c.firebasestorage.app',
    iosBundleId: 'com.example.beatrivalsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDmOWVCwUU980mMqglNqYIfiwzOxRP5MQ',
    appId: '1:250491374057:web:a04dfe4e7ab3f20ff86378',
    messagingSenderId: '250491374057',
    projectId: 'beatrivals-d8d2c',
    authDomain: 'beatrivals-d8d2c.firebaseapp.com',
    storageBucket: 'beatrivals-d8d2c.firebasestorage.app',
    measurementId: 'G-06WWHEXL39',
  );

}